### ISSUE TITLE
Not working on V19+

### ISSUE THREAD

**Issue by paodb** [vaadin-component-factory/vcf-date-range-picker-flow#23]
Trying to use the component in a Vaadin 19 or higher throws the following error:

```
Caused by: java.lang.NoSuchMethodError: 'void com.vaadin.flow.component.datepicker.GeneratedVaadinDatePicker.<init>(java.lang.Object, java.lang.Object, java.lang.Class, com.vaadin.flow.function.SerializableFunction, com.vaadin.flow.function.SerializableFunction)'
        at com.vaadin.componentfactory.EnhancedDateRangePicker.<init>(EnhancedDateRangePicker.java:134)
        at com.vaadin.componentfactory.EnhancedDateRangePicker.<init>(EnhancedDateRangePicker.java:122)
```

It seems that GeneratedVaadinDatePicker constructor has changed in the newest versions of the platform.

**Comment by osenbg** [comment]
Hello Paola,

we are also interested to get the component running on V 21 

Stefan
